apiVersion: v1
kind: Service
metadata:
  name: kafka-analyser
  namespace: <namespace>
  labels:
    app: kafka-analyser
spec:
  type: ClusterIP
  selector:
    app: kafka-analyser
  ports:
    - name: http
      port: 8003
      targetPort: 8003
