server {
    listen ${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    location /admin/ {
        try_files $uri $uri/ $uri.html /admin/index.html;
    }

    location /docs/ {
        try_files $uri $uri/ $uri.html /docs/index.html;
    }

    location /agents/ {
        try_files $uri $uri/ $uri.html /index.html;
    }
}
